### ISSUE TITLE
Issue with Sidebar Auto-Opening in Recent Versions of BMO Plugin

### ISSUE THREAD

**Issue by PandaNocturne** [longy2k/obsidian-bmo-chatbot#95] opened 2024-07-14 16:41 UTC
First and foremost, I would like to extend my heartfelt gratitude for developing the BMO plugin. In my opinion, it is the most useful GPT plugin available for Obsidian. However, I have encountered an issue with a recent version of the plugin.

The new version introduced a feature where the sidebar automatically opens and displays the BMO interface whenever I switch notes. While this functionality can be convenient in certain situations, I typically prefer to keep the sidebar collapsed. As a result, the auto-opening sidebar occasionally disrupts my writing flow.

I would like to inquire if there is a way to disable this feature, as it has been somewhat bothersome for my workflow. If there is a setting or a workaround to keep the sidebar from auto-opening, I would greatly appreciate your guidance.

Thank you once again for your excellent work on this plugin.

**Comment by longy2k** [comment] 2024-07-21 02:57
v2.3.2

Thank you for your feedback.

For now, I have only removed the auto focus on the view when deleting files. I am not sure if that relates to the note switching since I was not able to reproduce it.

If the issue is still reoccurring in this version, please explain step-by-step of what you're doing that leads to the view to activate.

Thanks again!

**Comment by longy2k** [comment] 2024-07-21 02:59
@BlackUdon

I have not tested opening files from .docx or closing file from launch application. I only removed a part of the function that relates to the delete file. 

I will see if I can reproduce these issue when I have time.

Thank you!

**Comment by PandaNocturne** [comment] 2024-07-22 06:16
@longy2k hank you, it is working well now.

**Closed** 2024-07-22 06:17 UTC
