### ISSUE TITLE
Messages end up in wrong order, sometimes disappear, "delete" deleting the wrong one

### ISSUE THREAD

**Issue by Madd0g** [longy2k/obsidian-bmo-chatbot#71] opened 2024-04-20 18:31 UTC
I'm playing locally with llama3 that recently came out, it has this annoying quirk of responding with nothing.

I think in those cases, the plugin gets confused a little, because I often get the bots response above mine, and once that happens, a lot more things break, like delete deleting the wrong chat-pair, my message disappearing, while the bot message remains, _really_ annoying side effects

maybe it puts the bot message in the wrong index first and upon first real token "fixes" it somehow?

These empty responses are VERY tolerable because of the new edit feature (it's so great!), but when it puts the response in the wrong order, it breaks a lot of functionality and I couldn't find any workarounds

I found myself waving the cursor over 3 consecutive empty bot messages, looking for the delete button, took me a while to realize that's only on the user message that's no longer visible...

**Comment by twalderman** [comment] 2024-04-20 18:51
I've seen this many times on various models. Since 2.x

**Comment by longy2k** [comment] 2024-04-21 00:00
Hey,

Sorry I have not been able to work on this project for over a month now. I have been busy with school and work.

For this particular issue, I have also noticed that my conversations tend to break the UI at any given moment.

In the meantime, my quick fix is to click on the 'BMO Chatbot' button in the ribbon bar. This will keep your current conversation but it will also rebuild the window.

I will be back working on BMO in a few weeks.

Thanks

**Comment by longy2k** [comment] 2024-05-23 21:16
I think one of the issue is that the response of the models in not trimmed.

Another issue is that using commands (e.g. `/save`, `/model`, and `/append`) broke the UI at times.

I resolved both of these issues in v2.1.0.

Let me know if you run into the same issue of messages ending up in the wrong order.

**Comment by longy2k** [comment] 2024-05-24 16:05
@Madd0g 

Please update to v2.1.1 and make sure you bypass the CORS policy for any Ollama servers connecting to Obsidian. You can follow these instructions: https://github.com/longy2k/obsidian-bmo-chatbot/wiki/How-to-setup-with-Ollama

Let me know if you got it working, thanks!

**Comment by Madd0g** [comment] 2024-05-24 21:24
that's weird, getting this now: Error fetching chat response from Ollama: ResponseError: invalid options: min_p

**Comment by twalderman** [comment] 2024-05-24 22:01
Min_p is not yet supported by ollama.  It will be soon.  It is supported by llamacpp. Leave the field empty and ignore any errors.

**Comment by Madd0g** [comment] 2024-05-24 23:27
>Leave the field empty and ignore any errors.

even touching the field sets a 0.0 value

when I deleted it from the settings completely - it still sends it and still errors

![image](https://github.com/longy2k/obsidian-bmo-chatbot/assets/1171003/ccf2dbe5-39ea-4231-b8e1-a941fd84a503)

**Comment by twalderman** [comment] 2024-05-24 23:32
- [ ] Yes it will throw an error. It should not affect responses though.  The ollama branch to expose min_p is not yet merged and is not in the release candidate so I suppose it will be in a subsequent release.  I'm seeing the same as you.  I do have a custom ollama build that is dated the does support min_p and in that version the non feature works.  Ignore the error when first-aiding any issues you are having.

**Comment by Madd0g** [comment] 2024-05-24 23:34
>It should not affect responses though

I don't get any response in the UI - I see the request failing with status 400

**Comment by twalderman** [comment] 2024-05-25 03:01
Please try making a fresh vault and see if it working as expected.  Also try 111434 first to verify.

**Comment by longy2k** [comment] 2024-05-26 23:18
@Madd0g 

Try updating Ollama to the latest version.

Another user faced the same issue (https://github.com/longy2k/obsidian-bmo-chatbot/issues/62#issuecomment-2132427088)

**Comment by Madd0g** [comment] 2024-05-27 07:04
I wish there was a command to update via cli. I never log in physically to that computer and that's why I'm always behind.

I updated ollama and it works now. Thank you, happy to have it working again!

**Closed** 2024-07-08 09:13 UTC
